# Generated by Django 5.0.6 on 2024-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navbar", "0003_books_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
