# Generated by Django 5.0.6 on 2024-07-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navbar", "0005_alter_books_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="slug",
        ),
    ]
